Add method to return numbers (int) of free planets and numbers (int) …
alaingilbert/pyogame pull request #110
Opened 2021-05-11 10:47 UTC by Systemac

…of total planets.

2021-05-11 10:48 UTC, Systemac commented
def numbers_planets(self):
        class Planets:
            nb_planets = self.landing_page.find('p', attrs={'class': 'textCenter'}).find('span').text
            free = int(nb_planets.split('/')[1]) - int(nb_planets.split('/')[0])
            total = int(nb_planets.split('/')[1])

        return Planets

2021-05-14 21:01 UTC, PiecePaperCode requested changes
nice work 👍
there a some changes i requestet. see the comments.
also look other id functions on how they deal with planets. it saves you an get request isntead of doing two.

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +    def numbers_planets(self):
what is this function returning.
its not clear by the code. i need to look up the html to know what it is doing. 
needs a clearer name

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> -            r'"(.*)\\u00b0C (.*) (.*) ',
looks like a bugfix to me.
i guess this will be different in other languages and regions too. i code for ger and eng servers.

**this** should be a list of conditions that loops over it and looks for a none response.
so you dint need an if statement outside by its own.

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +        if textContent3 is None:
make it a loop that checks all the textContent variants

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +    def spyreports(self, lastDateOfReport=None, firstpage=1, lastpage=30):
looks legit 
nice work

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +            except:
except should be more specific 
whats the error when the page dosent exist?
except YOUREXEPTION:

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +        header = {'Referer': f'{self.index_php}page=ingame&component=overview&cp={id}'}
you dont need this.
response session library already manages this for you.

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +        response = self.session.get(self.index_php,
ogame api always accepts cp prameter at the end. you can pass the planet id here. saving you a request that you dont need to do

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +        response = self.session.get(self.index_php,
use the cp parameter so you dont need to set a reffer header

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +        print(token_rename)
remove print statements

2021-05-14 21:01 UTC, PiecePaperCode commented on ogame/__init__.py
> +        )
return true or false

2021-05-16 07:05 UTC, Systemac commented on ogame/__init__.py
> +        header = {'Referer': f'{self.index_php}page=ingame&component=overview&cp={id}'}
I said to myself that too, I tried without, and without that, it modifies the first planet by default ...

2021-05-16 13:55 UTC, PiecePaperCode commented
https://github.com/alaingilbert/pyogame/pull/110/commits/7cfc1695c73bdd0920b9d538892805e57a2285fd
I refactored your function. planet numbers and gave it a bedder name

2021-06-30 10:50 UTC, Systemac commented on ogame/__init__.py
> -            r'"(.*)\\u00b0C (.*) (.*) ',
Look's like to already resolve ^^

2021-06-30 10:50 UTC, Systemac commented on ogame/__init__.py
> +        if textContent3 is None:
Same ^^

2021-06-30 10:51 UTC, Systemac commented on ogame/__init__.py
> +        response = self.session.get(self.index_php,
If I don't do that, it's the first planet that rename ^^

2021-06-30 10:53 UTC, Systemac commented on ogame/__init__.py
> +        print(token_rename)
Removed ^^

2021-06-30 10:58 UTC, Systemac commented on ogame/__init__.py
> +        )
Ok, it's return directly the status response of the post

2021-06-30 11:00 UTC, Systemac commented on ogame/__init__.py
> +        response = self.session.get(self.index_php,
Ok, but in this case, i need it to be sure of the selected planet

2021-06-30 11:01 UTC, Systemac commented on ogame/__init__.py
> +    def spyreports(self, lastDateOfReport=None, firstpage=1, lastpage=30):
Thank's so much

2021-06-30 11:03 UTC, Systemac commented on ogame/__init__.py
> +            except:
no exception, i just play off script kiddies, i just solved this : remove it ^^

2021-06-30 11:08 UTC, PiecePaperCode commented on ogame/test.py
> +            self.empire.build(ships.espionage_probe(), self.ids[0])
lol i wondered what happend there.
Thx alot of the bug fix

2021-06-30 11:08 UTC, PiecePaperCode approved these changes
Its well put toghether

Ill clone it and test it on local machine

2021-06-30 17:37 UTC, merged