Add convenience functions for planets + moons. Add build_time function.
alaingilbert/pyogame pull request #72
Opened 2020-07-24 20:46 UTC by CptBaradon

Added some convenience functions:
- name_by_planet_id
- id_by_planet_coords
- id_by_moon_name
- id_by_moon_coords

Added calculation of build time in seconds based on resources.

2020-07-25 11:04 UTC, PiecePaperCode approved these changes
love it great job

2020-07-26 11:41 UTC, CptBaradon commented
I added a new commit to this PR and merged the current dev aswell.
Should prevent merge conflicts.

2020-09-17 06:43 UTC, PiecePaperCode commented
Now we need to update the readme aswell

2020-09-24 23:23 UTC, PiecePaperCode requested changes

2020-09-24 23:23 UTC, PiecePaperCode commented on ogame/__init__.py
> +    def build_time(self, id, resources):
This is a function bedder suited on an different File named convenience or shortcut like in django.
All the convenience would be there that a bot dev would use all the time. __init__ is more for request

2020-09-24 23:24 UTC, PiecePaperCode commented on ogame/__init__.py
> +    def build_time(self, id, resources):
price from constants would be moved there too

2020-12-25 16:28 UTC, PiecePaperCode commented
closed due to inactivety

2020-12-25 16:28 UTC, closed without merging